# Generated by Django 4.1.5 on 2023-02-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invista_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='nivel',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
